---
language: csharp
solution: ./Daze.Api/Daze.Api.sln

# mono:
#  - latest
#  - latest # => "stable release"
#  - weekly # => "latest commits"

mono: none
dotnet: 1.0.1
dist: trusty

install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore ./Daze.Api/Daze.Api.sln

# script:
