
language: node_js

node_js:
  - lts/*

install:
    - npm install
    - npm install -g typescript
    - npm install -g codeclimate-test-reporter

script:
    - npm run build
    - npm run test

after_script:
    codeclimate-test-reporter < coverage/lcov.info
