// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Daze")>]
[<assembly: AssemblyDescriptionAttribute("The dazed programmer blog.")>]
[<assembly: GuidAttribute("A539B42C-CB9F-4a23-8E57-AF4E7CEE5BAA")>]
[<assembly: AssemblyProductAttribute("Daze")>]
[<assembly: AssemblyVersionAttribute("0.4.0.2")>]
[<assembly: AssemblyFileVersionAttribute("0.4.0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Daze"
    let [<Literal>] AssemblyDescription = "The dazed programmer blog."
    let [<Literal>] Guid = "A539B42C-CB9F-4a23-8E57-AF4E7CEE5BAA"
    let [<Literal>] AssemblyProduct = "Daze"
    let [<Literal>] AssemblyVersion = "0.4.0.2"
    let [<Literal>] AssemblyFileVersion = "0.4.0.2"
