// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Daze")]
[assembly: AssemblyDescriptionAttribute("The dazed programmer blog.")]
[assembly: GuidAttribute("A539B42C-CB9F-4a23-8E57-AF4E7CEE5BAA")]
[assembly: AssemblyProductAttribute("Daze")]
[assembly: AssemblyVersionAttribute("0.4")]
[assembly: AssemblyFileVersionAttribute("0.4")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Daze";
        internal const System.String AssemblyDescription = "The dazed programmer blog.";
        internal const System.String Guid = "A539B42C-CB9F-4a23-8E57-AF4E7CEE5BAA";
        internal const System.String AssemblyProduct = "Daze";
        internal const System.String AssemblyVersion = "0.4";
        internal const System.String AssemblyFileVersion = "0.4";
    }
}
